Add some colors
matt-hayward/olcPGEX_AdditionalColours pull request #3
Opened 2022-07-24 20:16 UTC by LoubiTek

2022-07-24 20:37 UTC, matt-hayward requested changes

2022-07-24 20:37 UTC, matt-hayward commented on olcPGEX_AdditionalColours.h
>  			PALE_DARK_PINK(130, 66, 133);
You need to change to semi-colon here to a comma.

2022-07-25 01:08 UTC, LoubiTek commented
Ok... Like this ?

2022-07-25 06:13 UTC, matt-hayward approved these changes

2022-07-25 06:13 UTC, merged